default:
  image: ubuntu
      
compile:ubuntu_latest:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  script:
    - cat /etc/lsb-release
    - apt-get update -qq
    - ln -sf /usr/share/zoneinfo/UTC /etc/localtime
    - apt-get -y install cmake g++ libzmq3-dev
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTS=ON
    - make -j${nproc}
    - 'echo "Compilation successful"'
    - cat /etc/lsb-release
      
compile:ubuntu_20:
  image: ubuntu:20.04
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  script:
    - cat /etc/lsb-release
    - apt-get update -qq
    - ln -sf /usr/share/zoneinfo/UTC /etc/localtime
    - apt-get -y install cmake g++ libzmq3-dev
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTS=ON
    - make -j${nproc}
    - 'echo "Compilation successful"'
    - cat /etc/lsb-release
      
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - apt-get update -qq
    - ln -sf /usr/share/zoneinfo/UTC /etc/localtime
    - apt-get -y install graphviz doxygen
    - dir="public"
    - echo "Deploy to $dir"
    - mkdir -p $dir
    - ls -lrth ./ 
    - ls -lrth $dir
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export MESYTEC_SOURCE=$PWD
    - mkdir website
    - cd website
    - $MESYTEC_SOURCE/documentation/make_doxygen.sh
    - mv html/* ../$dir/
  artifacts:
    paths:
      - public
