image: gitlab-registry.in2p3.fr/tkn/docker_tkn:ubuntu20

stages:
    - build

pages:
  stage: build
  script:
    - dir="public"
    - echo "Deploy to $dir"
    - mkdir -p $dir
    - ls -lrth ./ 
    - ls -lrth $dir
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export MESYTEC_SOURCE=$PWD
    - mkdir website
    - cd website
    - $MESYTEC_SOURCE/documentation/make_doxygen.sh
    - mv html/* ../$dir/
  artifacts:
    paths:
      - public
